version: "3.8"

services:
  geospatial:
    build: "./geospatial"
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=${PASSWORD}
    volumes:
      - ${SHARED}:/home/rstudio/shared
  shiny-verse:
    build: "./shiny-verse"
    ports:
      - "80:3838"
    environment:
      - APPLICATION_LOGS_TO_STDOUT=false
    volumes:
      - ${SHARED}/shinyapps:/srv/shiny-server/
