version: "3.8"

services:
  geospatial:
    build: "./geospatial"
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=${PASSWORD}
    volumes:
      - ${SHARED}:/home/awink/shared
      - ${SHARED}:/home/ghepp/shared
      - ${SHARED}:/home/rstudio/shared
  shiny-verse:
    build: "./shiny-verse"
    ports:
      - "80:3838"
    environment:
      - APPLICATION_LOGS_TO_STDOUT=false
    volumes:
      - ${SHARED}/shinyapps:/srv/shiny-server
  postgis:
    build: "./postgis"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - ${SHARED}/pgdata:/var/lib/postgresql/data
